# Setup
title:        Xinchengo's Github Pages
tagline:      This are some interesting things that I've been collecting till today.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Xinchen Li
  url:        https://xinchengo.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
