site_name: xinchengo 的博客
repo_url: https://github.com/xinchengo/xinchengo.github.io/

theme:
    name: 'material'
    language: zh
    
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至深色模式

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: 切换至浅色模式

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
    lang: zh
  - roamlinks
  - git-revision-date-localized:
    enable_creation_date: true
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xinchengo/
