site_name: xinchengo 的博客
site_url: https://lixinchen.cn/
repo_url: https://github.com/xinchengo/xinchengo.github.io/
edit_uri: edit/blog/docs/
copyright: Copyright &copy; 2021 - 2022 xinchengo

theme:
  name: "material"
  language: zh
  features:
    - navigation.tabs
    - navigation.sections

# Extensions
markdown_extensions:
  - smarty
  - footnotes
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.js
  - _static/extra.js

extra_css:
  - _static/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.15.3/dist/katex.min.css

plugins:
  - search:
      lang: zh
  - roamlinks
  - git-revision-date-localized:
      enable_creation_date: true
  - literate-nav:
      nav_file: summary.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xinchengo/
