name: Push to Blog Repository
on:
  push:
    branches:
      - blog
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Blog Repository
        uses: actions/checkout@v2
        with:
          ref: blog
          path: blog

      - name: Checkout the Main Repository
        uses: actions/checkout@v2
        with:
          ref: main
          path: pages
      
      # - name: Modify Raw Repository
     
      - name: Copy Files to the Main Repository
        run: |
          cp ./blog/index.md ./pages/docs/index.md
          rm -rf ./pages/docs/题解/
          mkdir ./pages/docs/题解/
          cp ./blog/tutorial/* ./pages/docs/题解/
          rm -rf ./pages/docs/笔记/
          mkdir ./pages/docs/笔记/
          cp ./blog/note/* ./pages/docs/笔记/

      - name: Commit to the Main Repository
        run: |
          cd pages
          MESSAGE=`date`
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "Commit on $MESSAGE"
          cd ..

      - name: Push to Main
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: "./pages"