name: Push to Github Pages
on:
  push:
    branches:
      - blog
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Blog Repository
        uses: actions/checkout@v2
        with:
          ref: blog
      
      - name: Modify the Repository
        run: |
          mkdir ./docs
          mv ./index.md ./docs/index.md
          mkdir ./docs/题解/
          mv ./tutorial/* ./docs/题解/
          mkdir ./docs/笔记/
          mv ./note/* ./docs/笔记/
          echo lixinchen.cn > ./docs/CNAME

      - name: Commit the Repository
        run: |
          MESSAGE=`date`
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "Commit on $MESSAGE"

      - name: Push the Repository
        uses: ad-m/github-push-action@master
        with:
          branch: blog
      
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      - name: Generate Mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          mkdocs gh-deploy --force

      - name: Revert Changes
        run: |
          git reset --hard HEAD~1
      
      - name: Push Back the Repository
        uses: ad-m/github-push-action@master
        with:
          branch: blog
          force: true