name: Push to Github Pages
on:
  push:
    branches:
      - blog
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Blog Repository
        uses: actions/checkout@v2
        with:
          ref: blog
          fetch-depth: 0
      
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Clone the Code Repository
        run: |
          git clone https://github.com/xinchengo/code.git

      - name: Generate Mkdocs
        run: |
          pip install mkdocs-material
          pip install mkdocs-roamlinks-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install mkdocs-literate-nav
          mkdocs gh-deploy --force
